### ISSUE TITLE
SMV Installation Error

### ISSUE THREAD

**Issue by jackyact** [ninjapapa/SmvSample1#5]
Run `MAVEN_OPTS` and `mvn clean install` after clone. Errors shown as
[INFO] Tests are skipped.
[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ smv ---
Discovery starting.
*** RUN ABORTED ***
  java.lang.UnsupportedClassVersionError: org/tresamigos/smv/CSVParser : Unsupported major.minor version 52.0
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
  ...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:15 min
[INFO] Finished at: 2016-03-10T14:31:43-08:00
[INFO] Final Memory: 31M/425M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project smv: There are test failures -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by ninjapapa** [comment]
What is the java version you use? Try "java -version".

**Comment by ninjapapa** [comment]
Ali: "Pretty sure Java v8 issue. Will try to reproduce today. Odd as usually same Java version is used to build as to run. So could be two Java versions on path( I.e.Java vs javac version mismatch)"

**Comment by jackyact** [comment]
result of `java -version`:
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

Need I install other version of java?
I'll download and rebuild it later today.

**Comment by ninjapapa** [comment]
How about `javac -version`?

**Comment by jackyact** [comment]
result of `javac -version`:
javac 1.8.0_74

**Comment by ninjapapa** [comment]
That is the problem. Need to figure out why "java" and "javac" has different versions. Sounds like you already have java installed by Ubuntu (OpenJDK), and you also installed Oracle JDK (or other java 8 JDK) manually. 

An easy way to fix is to make sure the path to java 8 (your `javac` command) is in front of the path to the `java` command. You can find their path by doing 
```shell
$ which java
$ which javac  
```
You can check you path 
```shell
$ echo $PATH
```

To change the order, you may need to edit your `.bashrc` file.

**Comment by jackyact** [comment]
changed the javac version and the build was successful.
